### ISSUE TITLE
fresh compile errors

### ISSUE THREAD

**Issue by majazaloznik** [Robinlovelace/spatial-microsim-book#48]
build.R:
install.packages("rgeos", "mipfp", "rgdal", "gridExtra")
uncomment lines 4128 to 4130 in book.Rmd (install GREGWT)
missing figure (row 863) figures/msim-schema.png"
missing file (row 4045) cache-smsim-in-R.RData"
(row 5133) error in "R/CakeMapInts.R" - data.frame different lenghts of columns(ints_df)

**Comment by Robinlovelace** [comment]
Should be fixed after this: https://github.com/Robinlovelace/spatial-microsim-book/commit/339006530911fb75c61f652a6692080d2132041f 

My build test:

```
cd /tmp/
git clone git@github.com:Robinlovelace/spatial-microsim-book.git
cd spatial-microsim-book/
R
source("build.R")
source("build.R") # for some reason needs to be done twice
```
Please let me know if there any more issues.

And many thanks for highlighting these bugs - overzealous .gitignore!
