### ISSUE TITLE
GREGWT can't be loaded

### ISSUE THREAD

**Issue by philmikejones** [Robinlovelace/spatial-microsim-book#72]
build.R currently requires GREGWT package but the link to download the source no longer exists: https://www.dropbox.com/s/l3n0gzl7s4a2zpy/GREGWT_1.4.tar.gz?dl=0 (see https://gitlab.com/emunozh/mikrosim)

**Comment by philmikejones** [comment]
06-alternative-approaches also can't be knitted because it requires GREGWT

**Comment by Robinlovelace** [comment]
@emunozh Can you have a look at this pls. Suggested solutions? Thanks.

**Comment by emunozh** [comment]
I will upload a new version of GREGWT to github today and implement that on the book. BTW you can retrieve the library directly from the git lab repro.

    wget https://gitlab.com/emunozh/mikrosim/blob/master/GREGWT_1.4.tar.gz

Sorry about the broken link! I will update the readme file on the gitlab repro.

**Comment by Robinlovelace** [comment]
Thanks Esteban - look forward to your PR, let me know if you want me to do it!

**Comment by emunozh** [comment]
I can do it but not now. I can do it on Thursday. I'm preparing a presentation for tomorrow. If it is just a matter of changing the link, I suppose you can do it quickly. There shouldn't be much difference with the new version... the underlying algorithm is the same. The new version is just much faster, but if you are just running a small example it won't really matter.

**Comment by emunozh** [comment]
@philmikejones Just created a pull request [#74](https://github.com/Robinlovelace/spatial-microsim-book/pull/74), if merged you will need to update the GREGWT library. Now you can install a development version via the `devtools` library.

    library(devtools)
    install_github("emunozh/GREGWT")

**Comment by Robinlovelace** [comment]
:+1: Thanks for flagging this issue @philmikejones and for the fix @emunozh. Any further issues with the book? Let me know.
