### ISSUE TITLE
Error in code: p6 05-sms-in-r

### ISSUE THREAD

**Issue by philmikejones** [Robinlovelace/spatial-microsim-book#75]
On page 6:
`ind_agg0 <- t(apply(cons, 1, function(x) x^0 * ind_agg))`
Returns this error:
`Error in x^0 : non-numeric argument to binary operator`

**Comment by philmikejones** [comment]
I've used
`ind_agg0 <- matrix(data = 1, nrow = n_zone, ncol = ncol(ind_cat))
for(i in 1:nrow(ind_agg0)) {
  ind_agg0[i, ] <- ind_agg
}`

So I can see what's going on, but would
`ind_agg0 <- t(apply(cons, 1, function(x) 1 * ind_agg))`
not work just as well?

**Comment by Robinlovelace** [comment]
Hi Phil, I can reproduce the error, but only if I don't run the code from Chapter 4 first. I think it states clearly that C. 4 is a prerequisite for running C. 5 so think it's OK.

Regarding your question, no it's not identical:

```
> weights1 <- weights2 <- weights # create addition weight objects
> head(ind_agg0)
     a0_49 a50+ m f
[1,]     2    3 3 2
[2,]     2    3 3 2
[3,]     2    3 3 2
```

vs

```
> ind_agg0 <- t(apply(cons, 1, function(x) 1 * ind_agg))
> head(ind_agg0)
     ind$agea0_49 ind$agea50+ ind$sexm ind$sexf
[1,]            2           3        3        2
[2,]            2           3        3        2
[3,]            2           3        3        2
```

To comprimise, I've done this:

```
# Create initial matrix of categorical counts from ind 
ind_agg0 <- t(apply(cons, 1, function(x) 1 * ind_agg))
colnames(ind_agg0) <- names(cons)
```

I imagine there's a better way still. Let me know if you spot it and keep the comments coming re. book!
